### ISSUE TITLE
--- unbound atom [defmacro] ---

### ISSUE THREAD

**Issue by DavidNemeskey** [blakemcbride/PC-LISP#1]
I tried to compile the [Cambridge/Edinburgh Morphological Analyzer and Dictionary System](https://www.cs.cmu.edu/Groups/AI/areas/nlp/morph/map/0.html) written in Franz lisp. However, I ran into the error in the title. I checked it in the interpreter, and indeed, `(defmacro)` doesn't seem to be implemented.

**Comment by blakemcbride** [comment]
defmacro is defined in pclisprc.l.  That file gets auto-loaded when the system starts up.  See BUILD.txt.  It describes the process.
