### ISSUE TITLE
-r -o (etc.) options

### ISSUE THREAD

**Issue by DavidNemeskey** [blakemcbride/PC-LISP#2]
The original Franz lisp had options `-r`, `-o` (amongst others). It would be nice if PC-LISP supported those too. A `-h` option (with the usual semantics) would help too.

**Comment by blakemcbride** [comment]
This system is not a complete clone of Franz Lisp.  It is close enough in most instances, however.  May I suggest the following.  The complete (mostly C) source to the real Franz Lisp is available.  See https://en.wikipedia.org/wiki/Franz_Lisp for many pointers.  I especially suggest http://www.aiai.ed.ac.uk/~jeff/franz-for-386.html  That last pointer is a system that did run on an early BSD environment.  I've long wanted to get it running again but just haven't had the time.
